hash-format = "sha256"

[[files]]
file = "README.md"
hash = "e672dfb8760bc9fc850380830657a2471a41e127573498aaff3e81a3157c8bab"

[[files]]
file = "config/aether-client.toml"
hash = "02245b02c6f6a64032e144abedcf66347094ca77bc94e73fed414424bbe3ddf3"

[[files]]
file = "config/cumulus_menus-client.toml"
hash = "ed577a5f879d797bac579fc0a558ba985b465bb492dab9411ead2939fe51ca73"

[[files]]
file = "config/yttr.css"
hash = "fb3f747fb8816a280b1c25a9a5ae14a2cea5baa59a7071edc4901bb150a471bc"

[[files]]
file = "kubejs/assets/kubejs/textures/item/crushed_raw_yttrium.png"
hash = "e7f346fdee6fb8e3f4b95bfd9124f255f4cc0455342e3a564fd1276037baea48"

[[files]]
file = "kubejs/config/client.properties"
hash = "f8e348c98f341e71834b2954049179498c25403d2cae9edf8e4ccbf25c8370aa"

[[files]]
file = "kubejs/config/common.properties"
hash = "3df12cec9b37d01efc6d04294444df18bb15d59bf69c8be7566839300e896498"

[[files]]
file = "kubejs/config/probe-settings.json"
hash = "76470005ebfc9e5beeb8e922c5b5516ae12132742b17a7d07ab5540299e08198"

[[files]]
file = "kubejs/server_scripts/recipes.js"
hash = "0399712328ea294fb19cfd29b9a1c839a3aa529b3aa72d873ab11d95704d2697"

[[files]]
file = "kubejs/server_scripts/removeRecipes.js"
hash = "8aef53d06528fab70d44ab7eae45fe767ba78073512bbd1a4771668f4a11691d"

[[files]]
file = "kubejs/server_scripts/rifleRecipes.js"
hash = "e2ec8875fd67f0e355830be5346357b808619c68279c24405478753a4ea57226"

[[files]]
file = "kubejs/startup_scripts/customItems.js"
hash = "ae942bf70e592f5fcc93c1cb0754305148c34e0b5c4b42fe7c033651031bae5f"

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
hash = "d6e7a16c16aef417eb27dd65b7fbf7b79bd8ad570072ffa21e90069c906c2e2d"
metafile = true

[[files]]
file = "mods/aether-protect-your-moa.pw.toml"
hash = "790e399b11031370efea4794909d629e5680f7e5012067439eb4047620783fde"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "bd60d7b7626f721293364020a12dd036c73ead7f5a5bb2069a2152d456f0f8a8"
metafile = true

[[files]]
file = "mods/animaticareforged.pw.toml"
hash = "5e2ed9b64d26d5fa3b361e0878cb32e75ecf6cc868ed043f7c61957acef0a993"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b218a766c81c7f0c4420db2f42d7b3f06831c124d2828247dd3ba4dd2ac8d759"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a7fa7c681c6bbc5d614b527c7f234153af5a54686013282ae918f8c1e41dfc23"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "1911b9f2bc9debccc66d7762932f66975f111695df46168fa80a628d31b0cbed"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "4beb8aa9c38dfa4d7cceaf5028495b89e71c78b34bc478906f0d1dbf356d7103"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "c6a778c45860c0d04d50bf9a30801b10beb50a35442a162bf2bec466a902b490"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "8ad21a02209e4b1b0a904774011bf5b3b5331b66dedc0505e29384b1fbf07a39"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1f0ad1ed71545dd138f5f1bd258a0c9e5c66dc803a924551f36a0d8573960e90"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "2e96f1be52d41fd238bed3b1bb76f031f2f61642a1645b830222b9dd41db44f1"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "d310976d135a61460de49815fdb348ecf722906b640d48f316a3e8ed29416231"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "16f04b164b9781d05acecada11db618dc48568545d4c9dcc8120c55008c200ed"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "718c9881fbe4219ad0b18bfeed55396399ae309d0a1d0cd2121f4b288106bb16"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c4402050d2a686cecc112aee451709d33c7c367021e6527a3786a0c458026d8f"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "6e28562d49f9998820e4aecccb846fd22b748f6e111612072eb5dc603416e37f"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "59c36a701c508b9a4c708bf76a8706ff341b19846231d66b0355ef7eb7aa5ca8"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "590f84c89626c00b07d4756183898671abb274f5ee987caab9da69507b10db04"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "5391ac307bbc73edb72e7eb11495af96e327eff1c02ff67d2ebbe615ca6766d7"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "882dd50766e02c0fd858eca69001399e9cce073035f10a6832ed3c4385648b32"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "077f07cd1941710c588714c96364fd445331908ae78c3f7475d79d8964aedf35"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "720a81bd0438266592e09f80945e354c56637db5311acf6b52c78ab43261a651"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c189f4f381070c3e52d0d94e7c963c6f2d59cc3a8d03b0aecd5f00bc3b0ab0a4"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "938ac0d044bf68cc2e73a2ac8966eaaa498606f18861647cb702342bd2aba4c4"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "8c1b55d29559d89437272f58baee1d142898b0a1a2a105f0d419cef208c3ce3d"
metafile = true

[[files]]
file = "mods/emi-create-schematics.pw.toml"
hash = "1d7a112bf4dcb4ecf851e3806c379ddd39bb4a1b5e8e1182c9b71116d003d0f3"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "de1a030b0828d22d0dc8678560436c9be79201b060d76fd38c80e0d388f27586"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "831ecf0f3b949b4389945a4331a1940788a890f6bc9c5d545a9dce2cd9242a4e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "8fcddfe7d1a05064a9abbb03577da95397a9fa6ae86eddc94d322e01b92314cd"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
hash = "a52b75a9ecc6702eaaced0d9b8b517b36f7aa8c4550d2dbd69a04a760f617f61"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "bc8a05efb224b15a51333ec45004ae4373133484a9cf48af1c065e9bde46d1e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9eb391a3ddd6b1fce680906177180763829461c0b79a209f141b333ba69fbd38"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4a5da1d5c42a0f82b8403d15e135a9b89fca6212ad022e48e36152e280f93b56"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "e91ef5a6af56e00a1d5ae4f0488401d35dbe37efb3b1d673d19bf20095dce3a5"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "31cfadba65d9939c205474c0c33f6f648705a9be842fedc03c98c7f5da154eb7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4acc2c7bde66e6cd4940978ce206bde20e2ce512b1bd2c3f669864555fa79a1a"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "afd697c4c2e25ed2bafee3f426448c7ac4f4af60b174450310691f22f78e12e4"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b3b13619f8d67cec19fe268d45c956d11aa4c68482e399cb83e84a9f546df972"
metafile = true

[[files]]
file = "mods/glassential.pw.toml"
hash = "0a6cfa7466bdbc93a6f0b6605fdbcce6c9006f3bbe59c5e28c196698ed6da89f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c0452b2f93522355316fb71583e6d4bb3c44aeada9d20eb8fb7b71bc8d7114c0"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "341db661ca9a73d65f9b46ee391beda46ab8d7a7a13127f4d693944236d6a32b"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "e45d31ebd2b2b8cc1139934ff4e881f5a76f589e97558c93fc0704a86102cd00"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0ba6ef04a4b6a7dcf44a47e211d7e46dc6930fdef06e85363ff66785279cd363"
metafile = true

[[files]]
file = "mods/just-blahaj.pw.toml"
hash = "e5d19a3bd91b0b88d78c277c7d23f4635f8d14c7902c5b95c19b4d08bfc5c9a7"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "2b815e905b26eb506c7f835dde6e23abddcbe3c7c9be3a4d11d9c13ad584737e"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "5da2157c4bc322dd70f0af213f34fe1963018da6fdafd7c2fbe5d921e348e6cb"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "7ca1201a262f62ae914d1bdb178845a957fbc85562e483c41d7c2ab48abd3537"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
hash = "ac199fe2b60df5a9210a52f2f4c7e1ef22d51012f878a27c3a63cdaf4ad743f1"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "98e80b668f218a6c1da83468e5798666f1e84fc34a8c844a29c3fe485422f11f"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
hash = "9da99e76d2ca75e06e82f7d5378d91b1db70292bf78019b64ebf64623e8965bc"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "feca94e94b280af2b8a1b6f417ae7b84de829913b74962015ef8ca55b54793c3"
metafile = true

[[files]]
file = "mods/map-atlases-forge.pw.toml"
hash = "5c77d7933a6023ab8a8f2ce3bfeb6a39531da7d83a8c6d4afc3a7638f1e53ec2"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "4e89107e6d81931530731f231aadb2f2b9d2fbe5c5a9078c0d5e38241b3bab55"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "8675da0dd391ce1de0165cf7d6052ce70f78db332fc60bcc87e55c070e3169b6"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "793e40dafda2ae3daa341a17c2275e0497a2444eb33d18988eed6a41cffbdf74"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b6b603c0ba0f1d441e57b62d11f61d766a0efcf3b082a9a03ccf381b5c9f03a3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "d29b209fde3072e8307f59278e949d103da853ff8ed62bf1f367338d5f4acc77"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "08169daf5277221516aa5b0dd07d95ecbc4ca3710b6b02b951fb6fc21b225901"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "cc61d25d40bb8da8c78f2ef42f5e7ee66118b0cf754e770794a9e048da15ee6b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "816c4af5ac97051e4fdd9101bde0568afb762d55d9370e917cfc717e463192e1"
metafile = true

[[files]]
file = "mods/norecipebookreborn.pw.toml"
hash = "d61cd41f0d1165679006b62dc8fb44d9a6894200a5cfe0b0c27180120f5f1c83"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-crops.pw.toml"
hash = "6f478786ae9dd220771224915da5df2e685d603df9d0ec25ebeb2be9054f8a25"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.pw.toml"
hash = "d865f7e79609b192302ce4ada550e01da3bc1e1323e4cfce6fdaba879faf08a4"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-extended.pw.toml"
hash = "2442d630dde3d90e0cd6e31c57693e53222b4edc32557a69edb7decdd24c94c4"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-nerf.pw.toml"
hash = "260ba91ca95346510018738ce7bd5b2815c83507d4e08b837e32f56df1eccd6d"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-trees.pw.toml"
hash = "8f64f1e7d6fb76f32b1398e2eed6aa42c9f3852333b5a9232f210f9b6569ba6e"
metafile = true

[[files]]
file = "mods/plonk.pw.toml"
hash = "73a2f78aaa77f6957f5e8f162b28e3dbf5ed8dd58bab7e197f8360731d31f518"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b5c660e93a9cc570ca02a75e0ebf5107960fb39949877e9af7886f0c14483c2"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "c25f64c7fcc892bf6f5bb8ae43a78eacb0125e2dca82429612a12f87dcff0eed"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "58f5287a228d8feeed9ff1110b71cea3520b7c26187fa957834b65ac28044bda"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "175e45d6308667112ecc404deaebc7116392c47eeebd657eda40ecb1317097f7"
metafile = true

[[files]]
file = "mods/sleeping-overhaul-2.pw.toml"
hash = "980e4db0ef96f0f140d7e1af78b389345800cddf9ba2c2244110b743f86c654a"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "5978490f9fa5fa34f5edcf64bf4189dd4c8c5d4c1da8cd78b85377f8db221e92"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "9e5c407a64785f46512746ca0e29d5316df35867d5c0c7273f5887116a05225c"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "b9fe9746798cfc81ebff09e9b0eab82ea8472210e893e1397174e899c2e4c44a"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "2ff54155d341809882b7237191d868e8b4a8f7e32a85ec04082cb13d0a301f0c"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9f50f48370676ae160d05940ed6cd7428fdb9d5135fb7021182495b13be78bd3"
metafile = true

[[files]]
file = "mods/toastbegone.pw.toml"
hash = "aa3a59666a1fb592e12f1da031762d32fdef7e4dd5cee39a8213b6c4c05f13b4"
metafile = true

[[files]]
file = "mods/yttr.pw.toml"
hash = "201fa0f4b4f97abcee405ab905fcdbeefdfdd19a688486620166a2b8d7b624b0"
metafile = true
