hash-format = "sha256"

[[files]]
file = "README.md"
hash = "94d8535b1a69ed74841ba386b5675cc585794847a31674fa94dc26dcc47071d6"

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
hash = "8e7f2282ce70b5a82bfe05304c30e71d6d3c26a29a75d6e1f31e85af8b86eb2e"
metafile = true

[[files]]
file = "mods/aether-protect-your-moa.pw.toml"
hash = "674a62706fa6f05d690c173f5199a591fef1a1a2b2d62668cd1bf70b4c530eb3"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "6f87edf40bf0be7e7e266f9e2ff0bf7584c6bedff7975bad3259a21a60d1e598"
metafile = true

[[files]]
file = "mods/aetheric-tetranomicon.pw.toml"
hash = "26a07a689e24d7fc9fd69370f01ff50b2ec5963d201265d42e1c61dcb0a3db0d"
metafile = true

[[files]]
file = "mods/animaticareforged.pw.toml"
hash = "3f0721e1aacc6c8aeb3f7930530865392bc05374476cefa5ed2d05aa897f5a65"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "258431b158c3adc8e7bf4ac8ea9cec20def2e3c373294488d72c238bcbd7538a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "02062a6b61e230e7debaf1c03d5e1e7203e427588fceb9f3d6ef8cad8062397e"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "14481081a9e233f4ba57df8a77ce028184818143eae1c73b60749ea482c912e9"
metafile = true

[[files]]
file = "mods/cb-multipart.pw.toml"
hash = "37eb5758f4500d08e2bca3a3a75849baf117287e1d6e22fb0fbfbb28a5ea7c92"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/codechicken-lib.pw.toml"
hash = "c93aa0b2389ae4dd6fbd83ffbca5fc2f6307885dd5a21e776fe4a74278e3966c"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "a2c5d820180d2610e5017e3f08957010e30cf05d50ee3180272dac6f969260cf"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "d8480ee1f6ae58fa389e502108bcde4936ca326d6dc2f1608b9af9ac141cb35a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "852ee3d5dea735c0c8f4c030edb06164863e7d27eef535c697f86a8b20a1cff0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a4c814876cd9046f9cdbe0a5967edff092adb8c28de2d717ce5fe469d6fbc9a2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/emi-create-schematics.pw.toml"
hash = "fd2e4fd4c29e54badbd039ce10b0a0f0f9388d40a9f0ca03c2346bb50d5b6cd0"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "3a728230bfbaf61c1fb3a102bcf320b63a0a132c149b0b827eaf1ce0a52e3fef"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "5d6004ca876efde3d87e789b18c6e3c54be63ccab8b733d3f1b7c74f39f29eda"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
hash = "f9f6ab1a6f68298710ca37f82503969531856c67138c4049f20c134d8b70dc55"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "16b4a8a6c29d642b83ccfb68729c6520928fef115551d43aa301da72ca9498cd"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5ac6fe9a921d8fa00456ec2e18da02ede5c0da424c5c5b57da1206feeac40ff6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7b32032b0892b53e1e5daf5410b78b4d98b7bdcbe2184f1d643098de36674865"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4c5ec7476521092a74d8ae1b894e44903a3d7834898674294f0ce4ddb040b251"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "5ee15a58d7403c4c93dc0f54226706596355dcc6312ec13d10f7ea9d4adb71ba"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "e47b4547b51bcd116aa7734ccd185a4edbcec4caf7ff80ef195ada4b727f5f15"
metafile = true

[[files]]
file = "mods/glassential.pw.toml"
hash = "1fc7843c63c6283bf057d21d0834e472623f827036afb23ad9f6ba7438bb23ae"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "835bd8b05a05ce6c0981ddc37c49e4c476aa0414cc2a5321fd9f8994193b6feb"
metafile = true

[[files]]
file = "mods/immersive-infinity.pw.toml"
hash = "c97a1b58b066eb9641cca9200194569b95e1e56eb434c73ada91f8052e2397ee"
metafile = true

[[files]]
file = "mods/immersive-portals-neoforge.pw.toml"
hash = "8c56189a235a058e9dfd8a1f6ffa449b1cfcdb957f77f07750ee203057025b9a"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "8afdabc2edf17a0eed4de3a8e25df147c82d1775cddb02cf7f47c0c0f59797e0"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "f8312021fd88a4952e1d50a2f156fab65314f87658d7153efc56be76a422d5cd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/just-blahaj.pw.toml"
hash = "470c59f728aa7cfea5c05b46d2201224e60e07437af1cf372fa1f17dcded85ec"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "90a70141bcec839b6a1aa647c91f97bb7b33b6b9e6ce6b3b18a4113aa7dff636"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "d99d1c2d31ef8198c37c853676c71017ed2304d267d0590cbcb6c3658f674d0f"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "b6ed220c9069f60704dbfe19fd55c976ca56ada35bcb6918c4ad226cd842b99c"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
hash = "e57ad3496f6185470581e5a3ec1a6ceb09d8cf88ccde6305c5e464332d0fe867"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "47b9410704efc0f8cb3b34a87d7019a013850775afe464e887b19ecf45eac0d3"
metafile = true

[[files]]
file = "mods/map-atlases-forge.pw.toml"
hash = "245b2e9a6498ed63673d4ca8e0c101f8adc9f0a8d24c8088923a3386fcf69fa5"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "c9f8bce06b85e4dbfdaecc7d0930bf7f4fabccc7967f867b7eb7acb8dd5b77a7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ade41e4315735aa9116a0222b332e03d3f8df6eea301764d40d0bdc40f5e8689"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f7f96cba7b6d9da8113c00b50ed4ced2e12f8b2266dd1a5524427fde64afb2e1"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "8dd17f19e28b517c1ce56a2024ece8a37ca9bc866079d23969cc3811577861a4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/mutil.pw.toml"
hash = "d60f6a6d46b66a76a6e3d185177a20cba42b83ba37f34db0fbe3c9babab7c837"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "362ead0883974a7de4dd711a75ccfe71b2ceadf172211934e8cd6084977c0f49"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "311e6ff7804f35deac9b3bd48bba8708590f1d8b6648048e7a021b4c5583d3fc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "b849dfdaaa3e4ad635fb16595bfd6ae03b83de0c02f5b06faafb24cc33926f3f"
metafile = true

[[files]]
file = "mods/norecipebookreborn.pw.toml"
hash = "4524ad33cc6485c574a6b2f13c0097e61fe4305815e9458376ec3f9b33f35c6f"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-crops.pw.toml"
hash = "58fa126079b9f120d9b70cc9676eda1fecbc515edd14123f57a88abd35645998"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.pw.toml"
hash = "82da9f309f7f4a70cba7885bc52f0723137bb9925a62e545db07b95be65870a0"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-extended.pw.toml"
hash = "a710d790426a1a8c087a08524ad6ef69a9132e9b13f79722c18a984f35e7026f"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-nerf.pw.toml"
hash = "92d707cccc2f435724a1c07f8a7e02eeda7a42490c8bbeb595c71bf2f8a0300f"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-trees.pw.toml"
hash = "e586ed7ece00777429172363892eb64d2dee76b41f5c5b84d0ac8e2bdcee7438"
metafile = true

[[files]]
file = "mods/plonk.pw.toml"
hash = "4f5853145de45ad21f44ff07f68337561561b9e59aa7bda3d5447f54fb9551e6"
metafile = true

[[files]]
file = "mods/project-red-core.pw.toml"
hash = "5cbc12354a9183ff5413ce4db81b28014049207f2cc815050776b295ab5ce404"
metafile = true

[[files]]
file = "mods/project-red-expansion.pw.toml"
hash = "004548c84d0235b0c547bf6fa79c308c9694caf3dc03faa39a5f0d662c97dc60"
metafile = true

[[files]]
file = "mods/project-red-exploration.pw.toml"
hash = "aca496b9d88e2a964ff830f16fec7fb9358e56e0ad4115bb404c4ca8fab20b51"
metafile = true

[[files]]
file = "mods/project-red-fabrication.pw.toml"
hash = "9b0038008e5fa886b2df85cdba9ef7b371ef08dea77cea2113947d035358b23d"
metafile = true

[[files]]
file = "mods/project-red-illumination.pw.toml"
hash = "33c719d40f4921fa804301d078be166ee3d4a7bd08c9c1281634062b8718b476"
metafile = true

[[files]]
file = "mods/project-red-integration.pw.toml"
hash = "8d58a3e519dfb00b7e494d3aaecb005f549b2491495507013fc5b309b49cd0ea"
metafile = true

[[files]]
file = "mods/project-red-transmission.pw.toml"
hash = "563f167ca45d026339e32310623fdf2daefd89c258936e32b566d2f46c404617"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "5b92406160d9ea8a61ddf111caaecb7f6283678e2c40b08b72dce3eeaf20dc96"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "874a064efc37398f5818a38666ea31263bd65ed0478b519b819f7a361bd0893e"
metafile = true

[[files]]
file = "mods/sleeping-overhaul-2.pw.toml"
hash = "48bf4a89a02f94b0a3e75340502c217a38501ce7873aefb13bb63bcb638ceb5b"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "82bb7cd6c8b68bb1831bb7c374bd316b6403cd01195d582f19c31076c908953a"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "75a60e6b443b351b7a4a78ffce7c71e44b3e20ca10c374aea1de516c785d6e2d"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "985d34e70842a5c8e0a8a4e35be894e5f5c6d0dcbe25f2a8f74a45616d32be33"
metafile = true

[[files]]
file = "mods/tetra-extras.pw.toml"
hash = "024f6280e7d8bad9de70cd5f03ff8ff4be112d0171dd4979c2ac52f7a9cabcb2"
metafile = true

[[files]]
file = "mods/tetra.pw.toml"
hash = "c7c0bf52ed0a44e8e71403a92da8503e298dc961c57671ae933f707ec807004d"
metafile = true

[[files]]
file = "mods/tetracelium.pw.toml"
hash = "1f9ed7d78a4e7263a46a7ff5095394e3932d526e71ba8bdf1cd64c6f3b2594d1"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "6f1d490b7da3e30a96bf49588f3e4a6989be3368478622959a3f1f4fbe54198b"
metafile = true

[[files]]
file = "mods/toastbegone.pw.toml"
hash = "4c9718dfae660a41c445a797c02055b28fe12305a11663c594c0744c74b04e8e"
metafile = true

[[files]]
file = "mods/yttr.pw.toml"
hash = "9e2958626a47b4794bc19a78c09986ffc7a71a8dd7a02012238d3a51291fcecd"
metafile = true
