name = "Alaspack"
author = "ur-alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10097e2ae5d77bf252aaae79f253d4691a78893024ff72bf8ebbaf4ce8ade456"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
