name = "Alaspack"
author = "ur-alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509f8bf72aeba29b54df3b6ed5617eca555dfb88fd645f838cb847067b4614df"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
