name = "Alaspack"
author = "ur-alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4facb82e0cbf3402caae5594b886ae44db4fe4766c3f32c449fee5218d9d0722"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
