name = "Alaspack"
author = "ur-alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c90dbd67539a258f2edd033658a52b4f17ea76da0087900f57018df889442220"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
