name = "Alaspack"
author = "ur-alas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5345047024938b73160580126415fba03b47ff70a33c8f0df8410892763c7e6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
